---
title: "R+port"
date: '`r paste0("LATEST UPDATE : (GMT+9) ",format(Sys.time(),tz = "Asia/Seoul"))`'
author: Allen Park
always_allow_html: true
output:
   rmdformats::readthedown:
    self_contained: true
    lightbox: true
    highlight: tango
---


# 글로벌 시황


```{r echo = FALSE, message = F, comment = NA, results = 'markup'}

options(warn = -1)
Sys.setenv(TZ = "Asia/Seoul")

'%ni%' = Negate('%in%')

if(weekdays(Sys.Date()) %ni% c("Saturday", "Sunday","Monday") & ("00:00:00" < format(Sys.time(), "%X")) & (format(Sys.time(), "%X") < "09:00:00")==TRUE) {
  DATE = format(Sys.Date()-1,"%Y/%m/%d",tz = "Asia/Seoul")
} else if(weekdays(Sys.Date())=="Saturday"){
  DATE = format(Sys.Date()-1,"%Y/%m/%d",tz = "Asia/Seoul")
} else if(weekdays(Sys.Date())=="Sunday"){
  DATE = format(Sys.Date()-2,"%Y/%m/%d",tz = "Asia/Seoul")
} else if(weekdays(Sys.Date()) == "Monday" & ("00:00:00" < format(Sys.time(), "%X")) & (format(Sys.time(), "%X") < "09:00:00") == TRUE){
  DATE = format(Sys.Date()-3,"%Y/%m/%d",tz = "Asia/Seoul")
} else {
  DATE = format(Sys.Date(),"%Y/%m/%d",tz = "Asia/Seoul")
}

{
  if(!require(sparkline)) install.packages("sparkline")
  if(!require(rvest)) install.packages("rvest")
  if(!require(formattable)) install.packages("formattable")
  if(!require(htmlwidgets)) install.packages("htmlwidgets")
}

library(sparkline); library(rvest); library(formattable)

ticker= c('INX','DJI','IXIC',
          'FTSE','GDAXI','FCHI',
          'SSEC','SZSC','N225','TWII','kospi',
          'GCcv1','CLcv1')

############################## FNCT ##############################

fin_data = function(ticker,datetype=NULL,time_length=NULL){
  
  if(!require(rvest)) install.packages('rvest'); library(rvest)
  if(!require(qdapRegex)) install.packages('qdapRegex'); library(qdapRegex)
  if(!require(lubridate)) install.packages('lubridate'); library(lubridate)
  if(!require(readr)) install.packages('readr'); library(readr)
  
  INDEX = c('KOSPI','KPI200','KOSDAQ')
  
  FINDEX = c('DJI','IXIC','DJT','NDX','INX','SOX','VIX','SSEC','SZSC','SSEA','SZSA','SSEB','SZSB','CSI100','CSI300','HSI','HSCE','N225','TWII',
             'TOPX','VNI','AXJO','BSESN',
             'HNXI','STOXX50E','GDAXI','FTSE','FTMIB','AEX','FCHI',
             'IRTS','BFX','PSI20','IBEX','ISEQ','OMXC20','OMXS30','OMXH25','ATG','BUX',
             'KLSE','JKSE','BVSP','MXX','MERV')
  
  FTINDEX = c('NQcv1','EScv1','RTYcv1',
              'SFCc1','HCEIc1','SSIcm1',
              'STXEc1','FDXc1','SINc1',
              'GCcv1','SIcv1','CLcv1')
  
  datetype = ifelse(is.null(datetype),'month',datetype)
  time_length = ifelse(is.null(time_length),'12',time_length)
  if(datetype=="year" & time_length>10) time_length = 10
  if(datetype=="day") time_length = NA
  '%ni%' = Negate('%in%'); ticker = ifelse(ticker %ni%  FTINDEX, toupper(ticker),ticker)
  
  if(datetype!="day"){
    
    if(ticker %in% INDEX){
      url = paste0('https://api.stock.naver.com/chart/domestic/index/',ticker,'?periodType=',datetype,'&range=',time_length)
    } else if(ticker %in% FINDEX){
      url = url = paste0('https://api.stock.naver.com/chart/foreign/index/.',ticker,'?periodType=',datetype,'&range=',time_length)
    } else if(ticker %in% FTINDEX){
      url = paste0('https://api.stock.naver.com/chart/foreign/futures/',ticker,'?periodType=',datetype,'&range=',time_length)
    } else if(ticker == "FUT"){
      url = paste0('https://api.stock.naver.com/chart/domestic/futures/FUT?periodType=',datetype,'&range=',time_length)
    } else {
      url = paste0('https://api.stock.naver.com/chart/domestic/item/',ticker,'?periodType=',datetype,'&range=',time_length)
    }
    
    ind = url %>%
      read_html() %>%
      html_nodes('body') %>%
      html_text(trim = TRUE) %>%
      rm_between(., "[", "]", extract=TRUE) %>%
      rm_between(., "{", "}", extract=TRUE) %>% .[[1]] %>%
      strsplit(x=.,split = ",") 
    
    df = data.frame()
    for (i in 1:length(ind)) {
      df[i,c(1:5)] = parse_number(ind[[i]])[c(3,4,5,2,6)]
      df[1,c(6,7)] = NA
      df[i,6] = ifelse(i==1,NA,
                       round(df[i,4]-df[i-1,4],digits = 2))
      df[i,7] = paste0(round((df[i,4]/df[i-1,4]-1)*100,digits = 2),"%")
      rownames(df)[i] = ind[[i]][1] %>% parse_number() %>% ymd() %>% as.character()
    }
    colnames(df) = c("Open","High","Low","Close","ACC.Vol","Chg","%Chg")
    
  } else if(datetype=="day"){
    
    if(ticker %in% INDEX){
      url = paste0('https://api.stock.naver.com/chart/domestic/index/',ticker,'?periodType=day')
    } else if(ticker %in% FINDEX){
      url = paste0('https://api.stock.naver.com/chart/foreign/index/.',ticker,'?periodType=day')
    } else if(ticker %in% FTINDEX){
      url = paste0('https://api.stock.naver.com/chart/foreign/futures/',ticker,'?periodType=day')
    } else if(ticker == "FUT"){
      url = 'https://api.stock.naver.com/chart/domestic/futures/FUT?periodType=day'
    } else {
      url = paste0('https://api.stock.naver.com/chart/domestic/item/',ticker,'?periodType=day')
    }
    
    ik = url %>%
      read_html() %>%
      html_nodes('body') %>%
      html_text(trim = TRUE) 
    
    ind = ik %>%
      rm_between(., "[", "]", extract=TRUE) %>% .[[1]] %>% .[1] %>%
      rm_between(., "{", "}", extract=TRUE) %>% .[[1]] %>%
      strsplit(x=.,split = ",") 
    
    marketstatus = ik %>%
      rm_between(., "{", "}", extract=TRUE) %>% .[[1]] %>%
      strsplit(x=.,split = ",") %>% .[[1]] %>% .[grep("marketStatus",x=.)] %>% 
      rm_between(.,'\"', '\"', extract=TRUE) %>% .[[1]] %>% .[2]
    
    df = data.frame()
    for (i in 1:length(ind)) {
      df[i,c(1,2)] = parse_number(ind[[i]])[c(2,3)]
      df[i,3] = marketstatus
      row.names(df)[i] = format(ymd_hms(parse_number(ind[[i]])[1]),"%H:%M")
    }
    colnames(df) = c("InteradayPrice","ACC.Vol","MARKET")
  }
  df
}

################################################################

dfw = data.frame()

indices = c('S&P500', "Dow Jones Industrial Average",
            "NASDAQ","FTSE100","DAX PERFORMANCE","CAC40",
            "SSE Composite INDEX","ShenZhen Component",
            "NIKKEI225", "TSEC Weighted Index","KOSPI",
            "GOLD","WTI")

dfw = data.frame("INDICES" = indices,
                 "Last Price" = NA,
                 "Chg" = NA,
                 'ChgP' = NA,
                 'Vol'=NA,
                 'Vol_Bar' = NA,
                 'Intraday Chart' = NA,
                 'MARKET' = NA)

ticker = c('INX','DJI','IXIC',
           'FTSE','GDAXI','FCHI',
           'SSEC','SZSC','N225','TWII',
           'kospi',"GCcv1","CLcv1")

for (i in 1:nrow(dfw)) {
  dfw[i,c(2:5)] = tail(fin_data(ticker[i]),1)[c(4,6,7,5)]
  dfn = fin_data(ticker[i],'day')
  dfw[i,c(6:8)] = c(as.character(htmltools::as.tags(sparkline(dfn[2:nrow(dfn),2]-dfn[1:nrow(dfn)-1,2],
                                                              type = "bar",width = 100))),
                    as.character(htmltools::as.tags(sparkline(dfn[[1]],
                                                              type = "line",width = 100))),
                    dfn[nrow(dfn),3])
}

```

<br>

## 미국 시황

```{r echo = FALSE, message = F, comment = NA, results = 'asis'}

dfus = dfw[1:3,] %>%
  formattable(.,align = c("l","r","c","c","r","c","c","c"),
                   list(
                     INDICES = formatter("span",style = x~style(font.weight = "bold")),
                     Chg = formatter("span", style = x ~ style(
                       font.weight = "bold",
                       color = ifelse(.[[3]] > 0,"#2a9688",
                                      ifelse(.[[3]] < 0,"#e35d5d","black")))),
                     ChgP = formatter("span", 
                                      style = x ~ style(color = ifelse(grepl(x=.[,4],"-")==TRUE , "red", "green")),
                                      x ~ icontext(ifelse(grepl(x=.[,4],"-")==TRUE, "arrow-down", "arrow-up"), x)),
                     MARKET = formatter("span",
                                        style = x ~ style(font.weight ="bold",
                                                          color = ifelse(x == "OPEN","green","red")))
                     
                   ))

out = as.htmlwidget(formattable(dfus))
out$dependencies = c(out$dependencies, htmlwidgets:::widget_dependencies("sparkline", "sparkline"))
out

####################################################################################
####################################################################################

url = 'http://www.nanumtrading.com/마켓뉴스/뉴욕-증시/' %>%
  read_html() %>%
  html_nodes('a') %>% html_attr('href') %>% .[78]

tex = url %>% 
  read_html() %>%
  html_nodes(xpath = '//*[@id="content"]/div[1]') %>%
  html_nodes("p") %>%
  html_text(trim = TRUE) %>%
  .[-which(.=="")] %>%
  .[grep("현지시간",.):length(.)]

for (i in 1:length(tex)) {
  cat(tex[i],"\n")
  cat("\n")
}

```


---

<br>

## 유럽 시황

```{r echo = FALSE, message = F, comment = NA, results = 'asis'}

dfeu = dfw[4:6,] %>%
  formattable(.,align = c("l","r","c","c","r","c","c","c"),
                   list(
                     INDICES = formatter("span",style = x~style(font.weight = "bold")),
                     Chg = formatter("span", style = x ~ style(
                       font.weight = "bold",
                       color = ifelse(.[[3]] > 0,"#2a9688",
                                      ifelse(.[[3]] < 0,"#e35d5d","black")))),
                     ChgP = formatter("span", 
                                      style = x ~ style(color = ifelse(grepl(x=.[,4],"-")==TRUE , "red", "green")),
                                      x ~ icontext(ifelse(grepl(x=.[,4],"-")==TRUE, "arrow-down", "arrow-up"), x)),
                     MARKET = formatter("span",
                                        style = x ~ style(font.weight ="bold",
                                                          color = ifelse(x == "OPEN","green","red")))
                     
                   ))

out = as.htmlwidget(formattable(dfeu))
out$dependencies = c(out$dependencies, htmlwidgets:::widget_dependencies("sparkline", "sparkline"))
out

####################################################################################
####################################################################################

url = 'http://www.nanumtrading.com/마켓뉴스/유럽-증시/' %>%
  read_html() %>%
  html_nodes('a') %>% html_attr('href') %>% .[78]

tex = url %>% 
  read_html() %>%
  html_nodes(xpath = '//*[@id="content"]/div[1]') %>%
  html_nodes("p") %>%
  html_text(trim = TRUE) %>%
  .[-which(.=="")] %>%
  .[grep("현지시간",.):length(.)]

for (i in 1:length(tex)) {
  cat(tex[i],"\n")
  cat("\n")
}

```

---

<br>

## 골드 시황

```{r echo = FALSE, message = F, comment = NA, results = 'asis'}

dfg = dfw[12,] %>%
  formattable(.,align = c("l","r","c","c","r","c","c","c"),
                   list(
                     INDICES = formatter("span",style = x~style(font.weight = "bold")),
                     Chg = formatter("span", style = x ~ style(
                       font.weight = "bold",
                       color = ifelse(.[[3]] > 0,"#2a9688",
                                      ifelse(.[[3]] < 0,"#e35d5d","black")))),
                     ChgP = formatter("span", 
                                      style = x ~ style(color = ifelse(grepl(x=.[,4],"-")==TRUE , "red", "green")),
                                      x ~ icontext(ifelse(grepl(x=.[,4],"-")==TRUE, "arrow-down", "arrow-up"), x)),
                     MARKET = formatter("span",
                                        style = x ~ style(font.weight ="bold",
                                                          color = ifelse(x == "OPEN","green","red")))
                     
                   ))

out = as.htmlwidget(formattable(dfg))
out$dependencies = c(out$dependencies, htmlwidgets:::widget_dependencies("sparkline", "sparkline"))
out

####################################################################################
####################################################################################

url = 'http://www.nanumtrading.com/마켓뉴스/주요-경제-뉴스/' %>%
  read_html() %>%
  html_nodes('a') %>%
  .[grep("금값",.)] %>% html_attr("href") %>% .[1]

tex = url %>% 
  read_html() %>%
  html_nodes(xpath = '//*[@id="content"]/div[1]') %>%
  html_nodes("p") %>%
  html_text(trim = TRUE) %>%
  .[-which(.=="")] %>%
  .[grep("현지시간",.):length(.)]

for (i in 1:length(tex)) {
  cat(tex[i],"\n")
  cat("\n")
}

```

---

<br>

## 국제 유가

```{r echo = FALSE, message = F, comment = NA, results = 'asis'}

dfcl = dfw[13,] %>%
  formattable(.,align = c("l","r","c","c","r","c","c","c"),
                   list(
                     INDICES = formatter("span",style = x~style(font.weight = "bold")),
                     Chg = formatter("span", style = x ~ style(
                       font.weight = "bold",
                       color = ifelse(.[[3]] > 0,"#2a9688",
                                      ifelse(.[[3]] < 0,"#e35d5d","black")))),
                     ChgP = formatter("span", 
                                      style = x ~ style(color = ifelse(grepl(x=.[,4],"-")==TRUE , "red", "green")),
                                      x ~ icontext(ifelse(grepl(x=.[,4],"-")==TRUE, "arrow-down", "arrow-up"), x)),
                     MARKET = formatter("span",
                                        style = x ~ style(font.weight ="bold",
                                                          color = ifelse(x == "OPEN","green","red")))
                     
                   ))

out = as.htmlwidget(formattable(dfcl))
out$dependencies = c(out$dependencies, htmlwidgets:::widget_dependencies("sparkline", "sparkline"))
out


####################################################################################
####################################################################################

url = 'http://www.nanumtrading.com/마켓뉴스/주요-경제-뉴스/' %>%
  read_html() %>%
  html_nodes('a') %>%
  .[grep("국제유가",.)] %>% html_attr("href") %>% .[1]

tex = url %>% 
  read_html() %>%
  html_nodes(xpath = '//*[@id="content"]/div[1]') %>%
  html_nodes("p") %>%
  html_text(trim = TRUE) %>%
  .[-which(.=="")] %>%
  .[grep("현지시간",.):length(.)]

for (i in 1:length(tex)) {
  cat(tex[i],"\n")
  cat("\n")
}


```

---

<br>

## 중국 시황

```{r echo = FALSE, message = F, comment = NA, results = 'asis'}

dfcn = dfw[7:8,] %>%
  formattable(.,align = c("l","r","c","c","r","c","c","c"),
                   list(
                     INDICES = formatter("span",style = x~style(font.weight = "bold")),
                     Chg = formatter("span", style = x ~ style(
                       font.weight = "bold",
                       color = ifelse(.[[3]] > 0,"#2a9688",
                                      ifelse(.[[3]] < 0,"#e35d5d","black")))),
                     ChgP = formatter("span", 
                                      style = x ~ style(color = ifelse(grepl(x=.[,4],"-")==TRUE , "red", "green")),
                                      x ~ icontext(ifelse(grepl(x=.[,4],"-")==TRUE, "arrow-down", "arrow-up"), x)),
                     MARKET = formatter("span",
                                        style = x ~ style(font.weight ="bold",
                                                          color = ifelse(x == "OPEN","green","red")))
                     
                   ))

out = as.htmlwidget(formattable(dfcn))
out$dependencies = c(out$dependencies, htmlwidgets:::widget_dependencies("sparkline", "sparkline"))
out

####################################################################################
####################################################################################

for (i in 1:4) {
  url[i] = paste0('http://www.newspim.com/news/lists/?category_cd=120040&page=',i*20-20)
  rurl = url[i] %>% read_html() %>%
    html_nodes(xpath = '//article[@class="thumbgroup"]') %>% 
    .[grep(pattern = "중국증시",x=.)] %>% html_node('a') %>% html_attr('href')
  
  if(length(rurl)!=0){
    url[i] = rurl %>% paste0('https://newspim.com',.)
  } else {
    url[i] = NA
  }
}

tex = url[which(!is.na(url))[1]] %>%
  read_html() %>%
  html_nodes('p') %>%
  html_text(trim = TRUE) %>%
  .[grep("=뉴스핌",x=.):tail(grep("newspim.com",x=.)-1,n=1)] 

tex[1] = substr(x=tex[1],gregexpr(pattern = '=뉴스핌',text=tex[1])[[1]][1]+14,nchar(tex[1]))

for (i in 1:length(tex)) {
  cat(tex[i],"\n")
  cat("\n")
}

```

---

<br>

## 일본 시황

```{r echo = FALSE, message = F, comment = NA, results = 'asis'}

dfjp = dfw[9,] %>%
  formattable(.,align = c("l","r","c","c","r","c","c","c"),
                   list(
                     INDICES = formatter("span",style = x~style(font.weight = "bold")),
                     Chg = formatter("span", style = x ~ style(
                       font.weight = "bold",
                       color = ifelse(.[[3]] > 0,"#2a9688",
                                      ifelse(.[[3]] < 0,"#e35d5d","black")))),
                     ChgP = formatter("span", 
                                      style = x ~ style(color = ifelse(grepl(x=.[,4],"-")==TRUE , "red", "green")),
                                      x ~ icontext(ifelse(grepl(x=.[,4],"-")==TRUE, "arrow-down", "arrow-up"), x)),
                     MARKET = formatter("span",
                                        style = x ~ style(font.weight ="bold",
                                                          color = ifelse(x == "OPEN","green","red")))
                     
                   ))

out = as.htmlwidget(formattable(dfjp))
out$dependencies = c(out$dependencies, htmlwidgets:::widget_dependencies("sparkline", "sparkline"))
out

####################################################################################
####################################################################################

content = "%s<br><br>"

tex = 'http://m.infostock.co.kr/daily/worldIndex.asp?mode=w&STYPE=JP' %>%
    read_html(encoding = 'euc-kr') %>%
    html_nodes(xpath = '//div[@class="txtContent"]') %>% as.character() %>%
    strsplit(x=.,split = '\r\n\t') %>% .[[1]] %>% .[3] %>% strsplit(x=.,split = "<br>") %>% .[[1]]
if(length(which(tex==""))==0){
  tex = tex
} else {
  tex = tex[-which(tex=="")]
}
dat = ifelse(length(grep("작성일자",tex)) == 0,DATE,
             tex[length(tex)] %>% substr(.,gregexpr('작성일자',.)[[1]][1]+7,nchar(.)-7) %>% .[1])
if(DATE == dat) {
  for (i in 1:(length(tex)-2)){
   cat(sprintf(content,tex[i]))
  }
} else {
  cat(sprintf(content,"마감시황은 장 마감 후 제공됩니다. 현재 준비 중 입니다."))
}

```

---

<br>

## 대만 시황

```{r echo = FALSE, message = F, comment = NA, results = 'asis'}

dftw = dfw[10,] %>%
  formattable(.,align = c("l","r","c","c","r","c","c","c"),
                   list(
                     INDICES = formatter("span",style = x~style(font.weight = "bold")),
                     Chg = formatter("span", style = x ~ style(
                       font.weight = "bold",
                       color = ifelse(.[[3]] > 0,"#2a9688",
                                      ifelse(.[[3]] < 0,"#e35d5d","black")))),
                     ChgP = formatter("span", 
                                      style = x ~ style(color = ifelse(grepl(x=.[,4],"-")==TRUE , "red", "green")),
                                      x ~ icontext(ifelse(grepl(x=.[,4],"-")==TRUE, "arrow-down", "arrow-up"), x)),
                     MARKET = formatter("span",
                                        style = x ~ style(font.weight ="bold",
                                                          color = ifelse(x == "OPEN","green","red")))
                     
                   ))

out = as.htmlwidget(formattable(dftw))
out$dependencies = c(out$dependencies, htmlwidgets:::widget_dependencies("sparkline", "sparkline"))
out

####################################################################################
####################################################################################

content = "%s<br><br>"

tex = 'http://m.infostock.co.kr/daily/worldIndex.asp?mode=w&STYPE=TW' %>%
    read_html(encoding = 'euc-kr') %>%
    html_nodes(xpath = '//div[@class="txtContent"]') %>% as.character() %>%
    strsplit(x=.,split = '\r\n\t') %>% .[[1]] %>% .[3] %>% strsplit(x=.,split = "<br>") %>% .[[1]]
if(length(which(tex==""))==0){
  tex = tex
} else {
  tex = tex[-which(tex=="")]
}
dat = ifelse(length(grep("작성일자",tex)) == 0,DATE,
             tex[length(tex)] %>% substr(.,gregexpr('작성일자',.)[[1]][1]+7,nchar(.)-7) %>% .[1])

if(DATE == dat) {
  for (i in 1:(length(tex)-2)){
   cat(sprintf(content,tex[i]))
  }
} else {
  cat(sprintf(content,"마감시황은 장 마감 후 제공됩니다. 현재 준비 중 입니다."))
}

```

---

<br>

## 코스피 시황

```{r echo = FALSE, message = F, comment = NA, results = 'asis'}

dfks = dfw[11,] %>%
  formattable(.,align = c("l","r","c","c","r","c","c","c"),
                   list(
                     INDICES = formatter("span",style = x~style(font.weight = "bold")),
                     Chg = formatter("span", style = x ~ style(
                       font.weight = "bold",
                       color = ifelse(.[[3]] > 0,"#2a9688",
                                      ifelse(.[[3]] < 0,"#e35d5d","black")))),
                     ChgP = formatter("span", 
                                      style = x ~ style(color = ifelse(grepl(x=.[,4],"-")==TRUE , "red", "green")),
                                      x ~ icontext(ifelse(grepl(x=.[,4],"-")==TRUE, "arrow-down", "arrow-up"), x)),
                     MARKET = formatter("span",
                                        style = x ~ style(font.weight ="bold",
                                                          color = ifelse(x == "OPEN","green","red")))
                     
                   ))

out = as.htmlwidget(formattable(dfks))
out$dependencies = c(out$dependencies, htmlwidgets:::widget_dependencies("sparkline", "sparkline"))
out

####################################################################################
####################################################################################

content = "%s<br><br>"

tex = 'http://m.infostock.co.kr/daily/koreaIndex.asp?mode=w&STYPE=KS1' %>%
    read_html(encoding = 'euc-kr') %>%
    html_nodes(xpath = '//div[@class="txtContent"]') %>% as.character() %>%
    strsplit(x=.,split = '\r\n\t') %>% .[[1]] %>% .[3] %>% strsplit(x=.,split = "<br>") %>% .[[1]]
if(length(which(tex==""))==0){
  tex = tex
} else {
  tex = tex[-which(tex=="")]
}
dat = ifelse(length(grep("작성일자",tex)) == 0,DATE,
             tex[length(tex)] %>% substr(.,gregexpr('작성일자',.)[[1]][1]+7,nchar(.)-7) %>% .[1])

if(DATE == dat) {
  for (i in 1:(length(tex)-2)){
   cat(sprintf(content,tex[i]))
  }
} else {
  cat(sprintf(content,"마감시황은 장 마감 후 제공됩니다. 현재 준비 중 입니다."))
}

```

---

<br>

**REFERENCE**

- ["뉴스핌"](http://newspim.com){target='blank'} <br>

- ["인포스탁"](http://infostock.co.kr/){target='blank'} <br>

- ["네이버금융"](http://finance.naver.com){target='blank'} <br>

- ["Finance Yahoo"](https://finance.yahoo.com/){target='blank'} <br>

- ["나눔트레이딩"](https://www.nanumtrading.com/){target='blank'} <br>
